---
  
inputFilesPath: r'data/input/' # r'path' turns path-like object into raw string
outputFilesPath: r'data/output/'
setbacksFile: 'setbacks.yaml'
commonTasksFile: 'commonTasks.yaml'
configFileName: 'config.yaml'
logFile: 'true_perf.log'